package mapping;
// Generated 3-feb-2016 17.17.06 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private String email;
     private String nome;
     private String cognome;
     private Date datacreazione;
     private Date datamodifica;

    public User() {
    }

	
    public User(String username, String password) {
        this.username = username;
        this.password = password;
    }
    public User(String username, String password, String nome, String cognome, Date datacreazione) {
       this.username = username;
       this.password = password;
       this.nome = nome;
       this.cognome = cognome;
       this.datacreazione = datacreazione;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCognome() {
        return this.cognome;
    }
    
    public void setCognome(String cognome) {
        this.cognome = cognome;
    }
    public Date getDatacreazione() {
        return this.datacreazione;
    }
    
    public void setDatacreazione(Date datacreazione) {
        this.datacreazione = datacreazione;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * @return the datamodifica
     */
    public Date getDatamodifica() {
        return datamodifica;
    }

    /**
     * @param datamodifica the datamodifica to set
     */
    public void setDatamodifica(Date datamodifica) {
        this.datamodifica = datamodifica;
    }




}


